### ISSUE TITLE
How do I remove the question mark characters from appearing in the console output?

### ISSUE THREAD

**Issue by cageygee3** [juhovh/mocha-jenkins-reporter#37] opened 2016-03-03 23:51 UTC
Whenever we run mocha tests through Jenkins, we get three question mark characters on each line that describes a single test:

http://s17.postimg.org/otfkckjkv/mocha_output.png

What's interesting is that if we click on "View as plain text", those characters don't appear and dots appear instead.

How do we fix this?

**Comment by juhovh** [comment] 2016-03-04 04:55
Have you enabled this?

Make sure to set the Color ANSI Console Output on and use for example xterm for the ANSI color map setting, in order to show the output colors nicely in Jenkins.

There could be a colorless version of the output but personally I like seeing the colors as well, because it makes it easier to find the failing tests.

**Comment by cageygee3** [comment] 2016-03-04 18:55
Yes, those settings were already set. "Color ANSI Console Output" is enabled and "ANSI color map" is set to xterm.

**Comment by juhovh** [comment] 2016-03-05 00:06
Hmm, ai need to check if I can reproduce, do you still see the colors or not in the output?

**Comment by cageygee3** [comment] 2016-03-05 00:42
No, I don't see any colors. Should I? I don't see any colors when I run the same tests in a terminal.

**Comment by cageygee3** [comment] 2016-03-18 17:51
Is there a way to disable colors? If disabling colors will get rid of those annoying question mark characters, I will happily give up colors in the output.

**Comment by cageygee3** [comment] 2016-04-01 21:02
Another data point: if I run my tests with the `--colors` command-line argument, the question mark characters show up in green. :smile:

**Comment by juhovh** [comment] 2016-04-02 06:12
Actually don't focus on colors, if the question marks are only in the beginning of the line this is most likely a character encoding issue. For example the tests are run with UTF-8 but Jenkins reads the report as latin1. There's nothing the reporter can do about this except print everything in ASCII only, but even then there might be some issues if the encodings are wrong.

**Comment by jvah** [comment] 2016-09-06 07:16
I think it's safe to conclude that this is a terminal configuration issue and not a reporter/mocha issue, so closing this.

**Closed by jvah** 2016-09-06 07:16 UTC

**Comment by Thatkookooguy** [comment] 2018-06-07 13:20
@kaiyoma This sounds as if the success mark, which is an emoji or a special character, isn't rendered correctly and instead it is being replaced with question marks.

or did I understand your original comment wrong?

**Comment by kaiyoma** [comment] 2018-06-07 17:46
It's actually a failure character (an 'X') but, yeah, basically what what you described. My project has since moved from mocha to jest, so I don't think we're using this reporter anymore, but we still see the question mark characters in the output, so there's an issue somewhere else.
